
ALTER TABLE evaluators 
ADD COLUMN IF NOT EXISTS family TEXT,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS is_patronus_managed BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS public_id TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
